id: AAA500844
title: 'The Tree of Awakening: A Prayer to the Great Abbot Śāntarakṣita'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:22:03.718802
  last_modified_at: 2022-03-01 02:22:03.718805
